name: CI
on:
 push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
test:
 runs-on: ubuntu-latest 
 steps:
  -name: check Uptime
   run : Uptime  
  -name: cpu info
   run : nproc  
  -name: kernel info 
   run: uname -r 
  
   
